### ISSUE TITLE
--profiles flag is not working

### ISSUE THREAD

**Issue by shashankmadhura** [livepeer/transcode-cli#3]
Error: unknown flag: --profiles

**Comment by hjpotter92** [comment]
> Error: unknown flag: --profiles

@shashankmadhura You have a typo there. The flag is `--profile` :)

**Comment by hjpotter92** [comment]
> Error: unknown flag: --profiles

@shashankmadhura can you provide how you're providing the flag? It is available to the `transcode` subcommand:

```
Usage:
  cli-transcoder transcode input.[ts|mp4] output.[ts|mp4] [flags]

Flags:
  -b, --bitrate uint        Bitrate (in Kbit)
  -f, --framerate string    Frame rate
  -g, --gop duration        Gop (time between keyframes)
  -h, --help                help for transcode
  -p, --presets string      List of transcoding presets, comma separated (P720p30fps16x9, etc)
  -o, --profile string      Profile (baseline,main,high)
      --profiles string     Names of the JSON file with transcoding configuration
  -r, --resolution string   Resolution (1280x720)

Global Flags:
  -a, --api-host string   Livepeer API host (default "livepeer.com")
  -k, --api-key string    Livepeer API key

```

**Comment by shashankmadhura** [comment]
-

   --profiles - file name with desired encoding profiles in JSON format.
   Example config.json
   <https://github.com/livepeer/cli-transcoder/blob/main/config.json>

**Comment by shashankmadhura** [comment]
sudo ./cli-transcoder transcode --api-key mykey
3MinutesixPackAbsWorkoutatHome.mp4 workout_trans.mp4 --profiles config.json

And my config.json file
[
    {
        "name": "240p0",
        "fps": 30000,
        "fpsDen": 1001,
        "bitrate": 250000,
        "width": 426,
        "height": 240,
        "gop": "2.0",
        "profile": "H264Baseline"
    },
    {
        "name": "360p0",
        "fps": 60000,
        "fpsDen": 1001,
        "bitrate": 800000,
        "width": 640,
        "height": 360,
        "gop": "2.0",
        "profile": "H264Main"
    },
    {
        "name": "480p0",
        "fps": 24000,
        "fpsDen": 1001,
        "bitrate": 1600000,
        "width": 854,
        "height": 480,
        "gop": "2.0",
        "profile": "H264High"
    }
]

**Comment by hjpotter92** [comment]
> sudo ./cli-transcoder transcode --api-key mykey 3MinutesixPackAbsWorkoutatHome.mp4 workout_trans.mp4 --profiles config.json 

That is indeed weird. Can you also provide the output for `./cli-transcoder --version`?

**Comment by shashankmadhura** [comment]
cli-transcoder version v0.1.5

**Comment by shashankmadhura** [comment]
It's working now. Downloaded the latest version. Thanks. Readme was
pointing to the old version.

**Comment by hjpotter92** [comment]
> It's working now. Downloaded the latest version. Thanks. Readme was pointing to the old version.

Oh! I'll mark the issue as resolved. There's a PR in review currently which updates the readme to always link to the latest release instead of a specific version.
